# Generated by Django 2.2.4 on 2020-05-09 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='liked_by',
            field=models.ManyToManyField(editable=False, related_name='liked_tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweeted_by',
            field=models.ManyToManyField(editable=False, related_name='retweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_ref',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
