# Generated by Django 3.0.6 on 2020-06-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200604_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
