# Generated by Django 3.0.6 on 2020-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200604_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140, unique=True)),
                ('most_recent_use', models.DateTimeField()),
                ('used_by', models.ManyToManyField(related_name='hashtags', to='homepage.Tweet')),
            ],
        ),
    ]
