# Generated by Django 2.2.4 on 2020-06-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
    ]
