# Generated by Django 2.2.4 on 2020-06-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200607_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='trending_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='last_hour_likes',
            field=models.IntegerField(default=0),
        ),
    ]
